# Generated by Django 2.2.3 on 2019-07-19 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SGMain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vertex',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vertex',
            name='vertex_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='SGMain.Vertex_Class'),
        ),
        migrations.AddField(
            model_name='preamble',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='path_entry',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMain.Path'),
        ),
        migrations.AddField(
            model_name='path_entry',
            name='vertex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SGMain.Vertex'),
        ),
        migrations.AddField(
            model_name='path',
            name='first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SGMain.Vertex'),
        ),
        migrations.AddField(
            model_name='path',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edge',
            name='edge_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SGMain.Edge_Class'),
        ),
        migrations.AddField(
            model_name='edge',
            name='preamble',
            field=models.ForeignKey(default='AAAAAAAAAA', on_delete=django.db.models.deletion.SET_DEFAULT, to='SGMain.Preamble'),
        ),
        migrations.AddField(
            model_name='edge',
            name='predecessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predecessor', to='SGMain.Vertex'),
        ),
        migrations.AddField(
            model_name='edge',
            name='successor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successor', to='SGMain.Vertex'),
        ),
        migrations.AddField(
            model_name='edge',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compilationlaunch',
            name='compilation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMain.CompilationData'),
        ),
    ]
